apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $files := .Files }}
  {{- range $path, $_ := $files.Glob "**.toml" }}
  {{ $path }}: |-
        {{ $files.Get $path }}
  {{- end }}