apiVersion: v1
kind: ConfigMap
metadata:
  name: virtuous-mink-configmap
data:
  myvalue: "Hello World"
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  toppings: |-
    {{- range $index,$topping := .pizzaToppings }}
    {{ $index }}: {{ $topping }}
    {{- end }}
  {{- if eq .drink "coffee" }}
  mug: "true"
  {{- end }}
  {{- end }}